### ISSUE TITLE
[Enhancement] Setup ES Lint and Actions workflow to lint on PR.

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#35]
### Description
We need to set up ESLint in our project to ensure code quality and consistency. Additionally, we will create a GitHub Actions workflow to automate the linting process on each push and pull request.

### Tasks
1. **Install ESLint**:
   - Run the following command to install ESLint as a dev dependency:
     ```bash
     npm install eslint --save-dev
     ```

2. **Initialize ESLint**:
   - Initialize ESLint to create a configuration file:
     ```bash
     npx eslint --init
     ```

3. **Configure ESLint**:
   - Create or update the `.eslintrc.json` file with the desired rules and settings. For example:
     ```json
     {
       "env": {
         "browser": true,
         "es2021": true,
         "node": true
       },
       "extends": [
         "eslint:recommended",
         "plugin:react/recommended"
       ],
       "parser": "babel-eslint",
       "parserOptions": {
         "ecmaFeatures": {
           "jsx": true
         },
         "ecmaVersion": 12,
         "sourceType": "module"
       },
       "plugins": [
         "react"
       ],
       "rules": {
         "react/react-in-jsx-scope": "off" // Customize as needed
       }
     }
     ```

4. **Add Lint Script to `package.json`**:
   - Update the `scripts` section of `package.json` to include:
     ```json
     "scripts": {
       "lint": "eslint ."
     }
     ```

5. **Create GitHub Actions Workflow**:
   - Create a new workflow file at `.github/workflows/ci.yml` with the following content:
     ```yaml
     name: CI

     on:
       push:
         branches:
           - main
           - development
       pull_request:
         branches:
           - main
           - development

     jobs:
       lint:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Node.js
             uses: actions/setup-node@v2
             with:
               node-version: '16'

           - name: Install dependencies
             run: npm install

           - name: Run ESLint
             run: npm run lint
     ```

6. **Test the Setup**:
   - Make a commit to ensure that ESLint runs correctly in the GitHub Actions workflow.

### Additional Notes
- Ensure that all contributors are aware of the linting rules.
- Consider integrating Prettier for code formatting to complement ESLint.

### References
- [ESLint Official Documentation](https://eslint.org/docs/user-guide/getting-started)
- [GitHub Actions Documentation](https://docs.github.com/en/actions)

---
